### ISSUE TITLE
"Revert all Changes" Throws error and does not work

### ISSUE THREAD

**Issue by knyghtmare** [knyghtmare/Unitmarker#1]
Only bug encountered so far.

**Comment by Toranks** [comment]
On 1.17.10 throws one obsolete warning, and an error trying to revert changes:
![imagen](https://user-images.githubusercontent.com/40789364/206962292-ec84d01a-e550-4ce5-a231-74b37498527c.png)

**Comment by knyghtmare** [comment]
That message overlap is so horrendously clumped that I cannot even make out what the actual message is

**Comment by Toranks** [comment]
20221212 11:00:05 warning deprecation: [unit]overlays ha quedado obsoleto y podría ser borrado en cualquier momento.; This warning is only triggered by the cases that *do* still work: setting [unit]overlays= works, but the [unit]overlays attribute will always be empty if WML tries to read it.
20221212 11:00:11 error wml: unknown conditional wml: [modify_unit]
20221212 11:00:11 error wml: unknown conditional wml: [if]

**Comment by Toranks** [comment]
Fixed:
[ef08baa9ea2ec4e75bf8c448b7a4b7e26146116d](https://github.com/knyghtmare/Unitmarker/pull/3)

**Comment by knyghtmare** [comment]
Closed by #3
