### ISSUE TITLE
Icons deviated, because uses obsolete positions

### ISSUE THREAD

**Issue by Toranks** [knyghtmare/Unitmarker#4]
Also, forces deviation of default loyal icons because has a file with the same name. Also, leader-crown-alt.png is a duplicated "trash" file that interferes with a mainline icon. Must be deleted both and move some pixels the rest of icons. It's easy so I will do it.

**Comment by Toranks** [comment]
Fixed on
https://github.com/knyghtmare/Unitmarker/pull/3

**Comment by knyghtmare** [comment]
Closed by #3
